#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "Building project..."
npm run build

if [ $? -ne 0 ]; then
  echo "Build failed. Commit aborted."
  exit 1
fi

git add .
echo "Build succeeded. Proceeding with commit."